# Generated by Django 6.0.8 on 2026-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('duration', models.PositiveIntegerField()),
                ('age_rating', models.CharField(max_length=10)),
            ],
        ),
    ]
