# Generated by Django 6.0.8 on 2026-08-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('locked', 'Locked'), ('booked', 'Booked')], default='available', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.show')),
            ],
        ),
    ]
